### ISSUE TITLE
[KYC-Match] MatchScoreResult type integer or float

### ISSUE THREAD

**Issue by rartych** [camaraproject/KnowYourCustomer#112]
**Problem description**
Currently the `MatchScoreResult` is defined as float but have the ranges 0-100 typical for percentage values.

```
    MatchScoreResult:
      type: number
      format: float 
      description: Indicates the similarity score assigned to the input value when it does not exactly match the value stored in the operator's system. This property shall only be returned when the value of the corresponding match field is `false`.
      minimum: 0
      maximum: 100
```

**Expected behavior**

Add description the value is percentage.

If more precision is not needed the `MatchScoreResult`  can be defined as as integer :

```
    MatchScoreResult:
      type: integer
```

**Alternative solution**
Keep  `MatchScoreResult` defined as float and change the range to 0-1 adding in the description that it should be limited to 2 or 3 decimal places.
```
      minimum: 0
      maximum: 1
```

**Additional context**
In Location Verification "MatchRate" is defined as integer.
https://github.com/camaraproject/DeviceLocation/blob/main/code/API_definitions/location-verification.yaml#L388C8-L388C15

**Comment by HuubAppelboom** [comment]
@rartych    We think the more precision is needed, and strongly suggest to keep it as a float.  If you play around a bit with Jaro Winkler and typical writing errors, you can see it makes quite a difference for example between 99,0 and 98,5.

I don't see the need to define this as between 0 and 1 in stead of 0 and 100, what problem does this solve ?

**Comment by rartych** [comment]
Other parameters named `score` in CAMARA are integers 0-100.
We should then add better documentation in the description to avoid confusion of API developers and API Consumers.

**Comment by ToshiWakayama-KDDI** [comment]
Hi @rartych , @HuubAppelboom , @KevScarr , all, 

Thanks for discussion. I do not have a strong opinion about Interger/Float, but do have concern about confusion of API developers and API consumers in understanding the number they receive. '0' and '100' can be clearly understood, however, I am not quite sure how they should understand the value between them.  For example, Jaro-winkler score 80/80.0 is good, or bad?  How about 30/30.0?  is it bad, or very bad?  Something like this.

Could we document some guidelines in the description?  Or, should we leave it wholly to API developers and API consumers?  Any views from those who are familiar with Jaro-winkler?

Best regards,
Toshi

**Comment by GillesInnov35** [comment]
hi all, we noticed at Orange that the code has not been updated according to the proposition which has been made above by @rartych 

```
MatchScoreResult:
      type: integer
```
bellow the current yaml code which is not compliant with swagger design recommendations: **_type  number_** could not be a **_integer format_**.

```
MatchScoreResult:
      type: number
      format: integer 
      description: Indicates the similarity score assigned to the input value when it does not exactly match the value stored in the operator's system. This property shall only be returned when the value of the corresponding match field is `false`.
      minimum: 0
      maximum: 100
```
it means that if I'm not wrong in kyc-match v0.2 MatchScoreResult attributes are still a float.
