### ISSUE TITLE
[KYC Match] Which fields are meant to be used for identification of the mobile phone user?

### ISSUE THREAD

**Issue by trehman-gsma** [camaraproject/KnowYourCustomer#135]
**Problem description**
Could you help to clarify which fields in the request body are meant to be used for identification purposes vs match purposes?

I had assumed that the access token or the `phoneNumber` field would be used to identify the mobile phone user (especially since `phoneNumber` does not have a corresponding match field in the response). However the [following error](https://github.com/camaraproject/KnowYourCustomer/blob/main/code/API_definitions/kyc-match.yaml#L497) implies that `idDocument` could also be used:

```
            IdDocumentRequired:
              value:
                status: 403
                code: KNOW_YOUR_CUSTOMER.ID_DOCUMENT_REQUIRED
                message: The idDocument is required to perform the properties validation
```

**Possible evolution**
Additional documentation to clarify the fields in the request that can be used to identify the mobile user. Or restructuring the request body to have an identity parent object and a parent match object.

cc @MsOlaAjibola @mbailadorpollo @pablosanuy
